import pandas as pd
planilha = pd.read_excel("BICHO1.xlsx")
alg1 = planilha['Alg1'].value_counts()
alg2 = planilha['Alg2'].value_counts()
alg3 = planilha['Alg3'].value_counts()
alg4 = planilha['Alg4'].value_counts()
print("Coluna Alg1 /n")
print(alg1)
print("Coluna Alg2 /n")
print(alg2)
print("Coluna Alg3 /n")
print(alg3)
print("Coluna Alg4 zn")
print(alg4)